authors:
  team:
    name: R-R-r
    description: Creator
    avatar: https://simpleicons.org/icons/ravelry.svg
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png